# NOTE: Change the pre-release to the release manually!
name: Pre-release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Check manifest.json for version
        run: |
          if ! grep -q '"version": "${{ github.ref_name }}"' manifest.json; then
            echo "manifest.json does not contain the latest version"
            exit 1
          fi
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno task build
      - run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --prerelease \
            --generate-notes \
            ./dist/main.js ./dist/manifest.json
        env:
          GITHUB_TOKEN: ${{ github.token }}
